config/routes.rb
Rails.application.routes.draw do

  resources :pts

  resources :patients, except: :index

  resource :pt_session, only: [:new, :create, :destroy]

  resource :patient_session, only: [:new, :create, :destroy]

  resources :pending_patients, only: [:new, :create, :destroy, :edit, :update]
end

app/models/concerns/has_password.rb
module HasPassword
  extend ActiveSupport::Concern

  included do
    attr_reader :password
    validates :password, length: { minimum: 6, allow_nil: true}
  end

  def password= password
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  module ClassMethods
    def find_by_credentials(email, password)
      person = self.find_by(email: email)
      return nil unless person
      person.password_digest.is_password?(password) ? person : nil
    end
  end
end

app/models/concerns/has_session.rb
module HasSession
  extend ActiveSupport::Concern

  included do
    validates :session_token, presence: true

    after_initialize :ensure_session_token
  end

  def ensure_session_token
    self.session_token = self.class.generate_token
  end

  def reset_session_token

  end

  module ClassMethods
    def generate_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  include HasPassword
  
  has_many(:clinics, through: :pts, source: :clinic)
  has_many(:sessions, as: :sessionable, dependent: :destroy)

  has_many(
  :pt_relationships,
  class_name: "PtPatient",
  foreign_key: :patient_id,
  dependent: :destroy
  )
  has_many(:pts, through: :pt_relationships, source: :pt)

end

app/models/pending_patient.rb
class PendingPatient < ActiveRecord::Base
  validates :name, :email, :verification_token, presence: true
  validates :email, uniqueness: true
  after_initialize :ensure_verification_token

  belongs_to(:pt)

  def ensure_verification_token
    self.verification_token = SecureRandom.urlsafe_base64
  end
end

app/models/pt.rb
class Pt < ActiveRecord::Base
  include HasPassword

  validates :clinic_id, :name, :phone_number, presence: true
  validates :email, presence:true, uniqueness: true

  belongs_to(:clinic)
  has_many(:sessions, as: :sessionable, dependent: :destroy)
  has_many(
  :patient_relationships,
  class_name: "PtPatient",
  foreign_key: :pt_id,
  dependent: :destroy
  )
  has_many(:patients, through: :patient_relationships, source: :patient)
  has_many(:pending_patients, dependent: :destroy)

end

app/models/pt_patient.rb
class PtPatient < ActiveRecord::Base
  validates :patient_id, :pt_id, presence: true

  belongs_to(:patient)
  belongs_to(:pt)
end

app/models/session.rb
class Session < ActiveRecord::Base

  validates :token, :sessionable_id, :sessionable_type, presence: true

  after_initialize :ensure_token

  def ensure_token
    self.token ||= self.class.generate_token
  end

  def self.generate_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionModule

  protect_from_forgery with: :exception

end

app/controllers/concerns/patient_session_module.rb
module PatientSessionModule
  extend ActiveSupport::Concern

  included do

  end

  def require_patient_log_in
    unless current_user.class == Patient
      flash[:errors] = ["Please log in first."]
      redirect_to new_patient_session_url
    end
  end


end

app/controllers/concerns/pt_session_module.rb
module PtSessionModule
  extend ActiveSupport::Concern


  def require_pt_log_in
    unless current_user.class == Pt
      flash[:errors] = ["Please log in first."]
      redirect_to new_pt_session_url
    end
  end

end

app/controllers/concerns/session_module.rb
require 'active_support/inflector'

module SessionModule
  extend ActiveSupport::Concern
  included do
    helper_method :current_user
  end

  def current_user
    current_session = Session.find_by(token: session[:session_token])
    return nil unless current_session
    current_session.sessionable_type.constantize.find(current_session.sessionable_id)
  end

  def log_in person
    current_session = person.sessions.create
    session[:session_token] = current_session.token
  end

  def log_out
    current_session = Session.find_by(token: session[:session_token])
    current_session.destroy
    session[:session_token] = nil
  end
end

app/controllers/patient_sessions_controller.rb
class PatientSessionsController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  include PatientSessionModule
  before_action :require_patient_log_in, only: :show
  def new
    @pending_patient = find_pending_patient
    @patient = Patient.new(get_pending_patient_params(@pending_patient))
    render :new
  end

  def create
    @patient = Patient.new(patient_params)
    @pending_patient = find_pending_patient
    if save_patient
      log_in(@patient)
      redirect_to patient_url(@patient)
    else
      flash.now[:errors] = @patient.errors.full_messages
      render :new
    end
  end

  def show
    @patient = Patient.find(params[:id])
    render :show
  end

  private
  def find_pending_patient
    PendingPatient.find_by(verification_token: params[:verification_token])
  end

  def save_patient
    PendingPatient.transaction do
      Patient.transaction do
        @patient.save
        @pending_patient.destroy
      end
    end
  end

  def get_pending_patient_params pending_patient
    pending_patient_params = {}
    pending_patient_params[:name] = pending_patient.name
    pending_patient_params[:email] = pending_patient.email
    pending_patient_params[:insurance_company] = pending_patient.insurance_company
    pending_patient_params
  end

  def patient_params
    params.require(:patient).permit(:name, :phone_number, :email, :password)
  end
end

app/controllers/pending_patients_controller.rb
class PendingPatientsController < ApplicationController
  def new
    @pending_patient = PendingPatient.new
    render :edit
  end

  def create
    @pending_patient = PendingPatient.new(pending_patient_params)
    if @pending_patient.save
      PatientVerificationMailer.verification_email(@pending_patient).deliver
      redirect_to pt_url(current_user)
    else
      flash.now[:errors] = @pending_patient.errors.full_messages
      render :new
    end
  end

  def edit
    @pending_patient = PendingPatient.find(params[:id])
    render :edit
  end

  def update
    @pending_patient = PendingPatient.find(params[:id])
    if @pending_patient.update(pending_patient_params)
      redirect_to pt_url(current_user)
    else
      flash.now[:errors] = @pending_patient.errors.full_messages
      render :edit
    end
  end

  def destroy
    @pending_patient = PendingPatient.find(params[:id])
    @pending_patient.destroy
    redirect_to pt_url(current_user)
  end

  private
  def pending_patient_params
    params.require(:pending_patient).permit(:name, :email, :insurance_company, :diagnosis)
          .merge(pt_id: current_user.id)
  end
end

app/controllers/pt_sessions_controller.rb
class PtSessionsController < ApplicationController
  include PtSessionModule
  
  before_action :require_pt_log_in, only: :destroy
  def new
    @pt = Pt.new
  end

  def create
    @pt = Pt.find_by_credentials(
      params[:pt][:email],
      params[:pt][:password]
    )
    if @pt
      log_in @pt
      redirect_to pt_url(@pt)
    else
      @pt = Pt.new
      flash.now[:errors] = "Incorrect Email, Password"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_pt_session_url # change later
  end

  private
  def user_params
    params.require(:pt).permit(:email, :password)
  end
end

app/controllers/pts_controller.rb
class PtsController < ApplicationController
  include PtSessionModule
  before_action :require_pt_log_in, only: [:show, :index]
  def new
    @pt = Pt.new
    render :new
  end

  def create
    @pt = Pt.new(pt_params)

    if @pt.save
      log_in(@pt)
      redirect_to pt_url(@pt)
    else
      flash.now[:errors] = @pt.errors.full_messages
      render :new
    end
  end

  def index

  end

  def show
    @pt = Pt.find(params[:id])
  end

  private
  def pt_params
    params.require(:pt).permit(:clinic_id, :name, :phone_number, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patient_sessions_helper.rb
module PatientSessionsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/pending_patients_helper.rb
module PendingPatientsHelper
end

app/helpers/pts_helper.rb
module PtsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/patients/new.html.erb
<%= form_for :patient, url: patients_url, method: :post do |f| %>
  <input type="hidden" name="verification_token" value="<%= params[:verification_token] %>">
  <label>Name:</label>
  <input type="text" name="patient[name]" value="<%= @patient.name %>">
  <br>
  <label>Email: </label>
  <input type="text" name="patient[email]" value="<%= @patient.email %>">
  <br>
  <label>Password: </label>
  <input type="password" name="patient[password]" value="<%= @patient.password %>">
  <br>
  <label >Phone Number:</label>
  <input type="text" name="patient[phone_number]" value="<%= @patient.phone_number %>">
  <br>
  <label >Insurance Company:</label>
  <input type="text" name="patient[insurance_company]" value="<%= @patient.insurance_company %>">
  <br>
  <input type="submit" value="Create Account!">
<% end %>

app/views/pending_patients/_form.html.erb
<% action_url = pending_patient.persisted? ? pending_patient_url(pending_patient) : pending_patients_url %>
<% submit_value = pending_patient.persisted? ? "Update Patient" : "Create New Patient" %>
<% header_title = pending_patient.persisted? ? "Edit Patient" : "Add Patient" %>
<% method = pending_patient.persisted? ? "patch" : "post" %>

<h3><%= header_title %></h3>
<%= form_for :pending_patient, url: action_url, method: method.to_sym do |f| %>
  <label>Name:</label>
  <input type="text" name="pending_patient[name]" value="<%= @pending_patient.name %>">
  <br>
  <label>Email: </label>
  <input type="text" name="pending_patient[email]" value="<%= @pending_patient.email %>">
  <br>
  <label >Diagnosis:</label>
  <input type="text" name="pending_patient[diagnosis]" value="<%= @pending_patient.diagnosis %>">
  <br>
  <label >Insurance Company:</label>
  <input type="text" name="pending_patient[insurance_company]" value="<%= @pending_patient.insurance_company %>">
  <br>
  <input type="submit" value="<%= submit_value %>">
<% end %>

app/views/pending_patients/edit.html.erb
<%= render "form", pending_patient: @pending_patient %>

app/views/pending_patients/new.html.erb
<%= render "form", pending_patient: @pending_patient %>

app/views/pts/new.html.erb
<h3>Create Account</h3>

<%= form_for :pt, url: pts_url, method: :post do |f| %>
  <input type="hidden" name="pt[clinic_id]" value="1">
  <label>Name:</label>
  <input type="text" name="pt[name]" value="<%= @pt.name %>">
  <br>
  <label>Email: </label>
  <input type="text" name="pt[email]" value="<%= @pt.email %>">
  <br>
  <label>Password: </label>
  <input type="password" name="pt[password]" value="<%= @pt.password %>">
  <br>
  <label >Phone Number:</label>
  <input type="text" name="pt[phone_number]" value="<%= @pt.phone_number %>">
  <br>
  <input type="submit" value="Create Account!">
<% end %>

app/views/pts/show.html.erb
<h1>Welcome, <%= @pt.name %> </h1>

<table>
  <tr>
    <th>Patient Name:</th>
    <th>Email:</th>
    <th>Diagnosis</th>
  </tr>
  <% @pt.pending_patients.each do |pending_patient| %>
    <tr>
      <td><%= pending_patient.name %></td>
      <td><%= pending_patient.email %></td>
      <td><%= pending_patient.diagnosis %></td>
      <td><%= button_to "Edit", edit_pending_patient_url(pending_patient), method: :get %></td>
      <td><%= button_to "Delete", pending_patient_url(pending_patient),
      method: :delete %></td>
    </tr>
  <% end %>
  <% @pt.patients.each do |patient| %>
    <tr>
      <td><%= link_to patient.name, patient_url(patient) %></td>
      <td><%= patient.email %></td>
      <td><%= patient.diagnosis %></td>
    </tr>
  <% end %>
</table>


<%= button_to "Add Patient", new_pending_patient_url, method: :get %>